<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="cyberbrick_arm">

  <!-- Properties -->
  <xacro:property name="base_height" value="0.05"/>
  <xacro:property name="base_radius" value="0.04"/>
  <xacro:property name="link1_length" value="0.08"/>
  <xacro:property name="link2_length" value="0.08"/>
  <xacro:property name="gripper_length" value="0.04"/>

  <!-- Materials -->
  <material name="orange">
    <color rgba="1.0 0.5 0.0 1.0"/>
  </material>
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>
  <material name="dark_grey">
    <color rgba="0.3 0.3 0.3 1.0"/>
  </material>

  <!-- World link (fixed point) -->
  <link name="world"/>

  <!-- Base link -->
  <link name="arm_base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="arm_base_joint" type="fixed">
    <parent link="world"/>
    <child link="arm_base_link"/>
    <origin xyz="0.3 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Servo 1: Base rotation (yaw) -->
  <link name="arm_link1">
    <visual>
      <geometry>
        <box size="0.03 0.03 ${link1_length}"/>
      </geometry>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      <material name="orange"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.03 0.03 ${link1_length}"/>
      </geometry>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="arm_joint1" type="revolute">
    <parent link="arm_base_link"/>
    <child link="arm_link1"/>
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="10" velocity="1.0"/>
  </joint>

  <!-- Servo 2: Shoulder (pitch) -->
  <link name="arm_link2">
    <visual>
      <geometry>
        <box size="0.025 0.025 ${link2_length}"/>
      </geometry>
      <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.025 0.025 ${link2_length}"/>
      </geometry>
      <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.08"/>
      <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.00005" iyz="0" izz="0.00005"/>
    </inertial>
  </link>

  <joint name="arm_joint2" type="revolute">
    <parent link="arm_link1"/>
    <child link="arm_link2"/>
    <origin xyz="0 0 ${link1_length}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="${pi}" effort="10" velocity="1.0"/>
  </joint>

  <!-- Servo 3: Gripper -->
  <link name="gripper_base">
    <visual>
      <geometry>
        <box size="0.02 0.04 0.02"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.02 0.04 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.03"/>
      <inertia ixx="0.00001" ixy="0" ixz="0" iyy="0.00001" iyz="0" izz="0.00001"/>
    </inertial>
  </link>

  <joint name="gripper_base_joint" type="fixed">
    <parent link="arm_link2"/>
    <child link="gripper_base"/>
    <origin xyz="0 0 ${link2_length}" rpy="0 0 0"/>
  </joint>

  <!-- Left finger -->
  <link name="left_finger">
    <visual>
      <geometry>
        <box size="0.01 0.005 ${gripper_length}"/>
      </geometry>
      <origin xyz="0 0 ${gripper_length/2}" rpy="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.01 0.005 ${gripper_length}"/>
      </geometry>
      <origin xyz="0 0 ${gripper_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001"/>
    </inertial>
  </link>

  <joint name="left_finger_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="left_finger"/>
    <origin xyz="0 0.015 0.01" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="0" upper="0.015" effort="10" velocity="0.5"/>
  </joint>

  <!-- Right finger -->
  <link name="right_finger">
    <visual>
      <geometry>
        <box size="0.01 0.005 ${gripper_length}"/>
      </geometry>
      <origin xyz="0 0 ${gripper_length/2}" rpy="0 0 0"/>
      <material name="grey"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.01 0.005 ${gripper_length}"/>
      </geometry>
      <origin xyz="0 0 ${gripper_length/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001"/>
    </inertial>
  </link>

  <joint name="right_finger_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="right_finger"/>
    <origin xyz="0 -0.015 0.01" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <limit lower="0" upper="0.015" effort="10" velocity="0.5"/>
    <mimic joint="left_finger_joint"/>
  </joint>

  <!-- Gazebo control plugin -->
  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <ros>
        <namespace>/arm</namespace>
      </ros>
      <parameters>$(find cyberbrick_description)/config/arm_controllers.yaml</parameters>
    </plugin>
  </gazebo>

  <!-- Transmission for joints -->
  <transmission name="arm_joint1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="arm_joint1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="arm_joint1_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="arm_joint2_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="arm_joint2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="arm_joint2_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="gripper_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_finger_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="gripper_motor">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
